apiVersion: v1
kind: Namespace
metadata:
  name: qemu-guest-agent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: qemu-ga-talos
  namespace: qemu-guest-agent
spec:
  selector:
    matchLabels:
      name: qemu-ga-talos
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: qemu-ga-talos
    spec:
      containers:
      - image: ghcr.io/crisobal/qemu-guest-agent-talos:0.5.0
        imagePullPolicy: IfNotPresent
        name: qemu-ga-talos
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/virtio-ports
          name: virtio
        - mountPath: /etc/talos
          name: talosconfig
          readOnly: true
        - mountPath: /var/run/secrets/talos.dev
          name: talos-secrets
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/virtio-ports
          type: ""
        name: virtio
      - name: talosconfig
        secret:
          optional: true
          secretName: talosconfig
      - name: talos-secrets
        secret:
          secretName: qemu-guest-agent-talos-secrets
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
    name: qemu-guest-agent-talos-secrets
    namespace: qemu-guest-agent
spec:
    roles:
        - os:admin
---

